version: "3.1"

# See https://blog.sonatype.com/using-sonatype-nexus-repository-3-part-1-maven-artifacts
services:
  nexus:
    container_name: nexus3
    image: sonatype/nexus3
    volumes:
      - ./data:/nexus-data
    network_mode: host
    env_file: .env
    restart: unless-stopped
