version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-3.12
    env_file:
      - .env
    restart: unless-stopped
    hostname: rabbitmq
    volumes:
      - ./data/mnesia:/var/lib/rabbitmq/mnesia
    network_mode: host
