---
- name: Install Node.js from tarball
  hosts: nodejs
  vars:
    nodejs_version: 16.19.1
    nodejs_tarball_url: https://nodejs.org/download/release/v{{ nodejs_version }}/node-v{{ nodejs_version }}-linux-x64.tar.gz
    nodejs_install_dir: /opt/node-v{{ nodejs_version }}-linux-x64
  tasks:
    - name: Download Node.js tarball
      get_url:
        url: "{{ nodejs_tarball_url }}"
        dest: "/tmp/node-v{{ nodejs_version }}.tar.gz"

    - name: Extract Node.js tarball
      become: yes
      unarchive:
        src: "/tmp/node-v{{ nodejs_version }}.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Change ownership of Node.js installation directory
      become: yes
      file:
        path: "{{ nodejs_install_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Add Node.js binary directory to PATH
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: 'export PATH="$PATH:{{ nodejs_install_dir }}/bin"'
        state: present
        create: yes
