---
- hosts: docker
  name: Install Docker
  tasks:
    # https://docs.docker.com/engine/install/ubuntu/#installation-methods
    - name: Install packages to allow apt to use a repository over HTTPS
      become: true
      apt:
        name:
          - ca-certificates
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get Ubuntu release version
      shell: lsb_release -cs
      register: ubuntu_version

    - name: Get architecture
      shell: dpkg --print-architecture
      register: architecture

    - name: Add Docker repository
      become: true
      apt_repository:
        repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present
        filename: docker

    - name: Install Docker engine
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install docker-compose from official github repo
      become: true
      when: install_docker_compose == true
      get_url:
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Add current user to docker group
      become: true
      when: add_current_user_to_docker_group == true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
