version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.40.0
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      - ./data/prometheus/:/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - "9093:9093"
    restart: unless-stopped
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - "--config.file=/etc/alertmanager/config.yml"
  grafana:
    image: grafana/grafana:9.4.7
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/:/var/lib/grafana/
