# standalone
version: "3.1"

services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000 # tcp agent
