version: "3.6"

services:
  runner-1:
    image: gitlab/gitlab-runner:alpine3.13-v14.8.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/:/etc/gitlab-runner/
    network_mode: host
