# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  public_key_file = "#{Dir.home}/.ssh/id_rsa.pub"
  instance_name = "ubuntu-18.04"

  # define a scope for each instance
  config.vm.define instance_name do |ins|
    ins.vm.box = "hashicorp/bionic64"
    ins.vm.hostname = instance_name
    ins.vm.network "private_network", ip: "192.168.56.184"

    ins.vm.provider "virtualbox" do |vb|
      vb.name = instance_name
      vb.memory = 2048
      vb.cpus = 2
    end

    ins.vm.provision "shell" do |s|
      public_key_content = File.readlines(public_key_file).first.strip
      s.inline = <<-SHELL
        # add current user public key to vagrant virtual machine
        echo #{public_key_content} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end

  end

end
