global:
  resolve_timeout: 5m

route:
  receiver: "telegram"

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "xxxxxxxxxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
        chat_id: 1111111111
